stages:
  - build
  - docs
  - deploy_docs
  - test

.excl_runner:
  tags: [excl]

variables:
  IRIS_INSTALL_ROOT: $CI_PROJECT_DIR/install
  IRIS_TESTING_PATH: code.ornl.gov/brisbane/iris-tests.git

build-job:
  extends: [.excl_runner]
  stage: build
  before_script:
    - module load cmake
    - module load gnu
  script:
    - echo "Installing iris to $CI_PROJECT_DIR/install"
    - bash build.sh

docs-job:
  tags: [devdocs]
  stage: docs
  before_script:
    - source /auto/ciscratch/conda/etc/profile.d/conda.sh
    - conda env create --force -p ./envs -f docs/sphinx/environment.yml
    - conda activate ./envs
  script:
    - cd docs/sphinx/source
    - python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
  artifacts:
    paths:
      - docs/sphinx/source/_build/html

.deploy_docs_common:
  tags: [devdocs]
  stage: deploy_docs
  needs: [docs-job]
  script:
    rsync -a docs/sphinx/source/_build/html ~/www/brisbane/iris

deploy_docs-job:
  extends: .deploy_docs_common
  only:
    refs:
      - ornl_main

deploy_docs_manual-job:
  extends: .deploy_docs_common
  when: manual

test-job:
  extends: [.excl_runner]
  stage: test
  allow_failure: true
  before_script:
    - module load cmake
    - module load gnu
  script:
    - echo "Installing iris to $CI_PROJECT_DIR/install"
    - bash build-coverage.sh
    - echo $CI_REPOSITORY_URL
    - echo $CI_PROJECT_PATH
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${IRIS_TESTING_PATH}
    - source $IRIS_INSTALL_ROOT/setup.source
    - cd iris-tests
    - mkdir build
    - cd build
    - cmake ..
    - make --ignore-errors
    - make test
  after_script:
    - module load cmake
    - module load gnu
    - module load python
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install gcovr==5.0 # There seems to be a bug for newer versions of gcovr.
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --gcov-ignore-parse-errors
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
